name: Test

on:
  push:
    branches: [ resolve_unit_tests ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '**/.gitignore'
      - '**/.editorconfig'
  pull_request:
    branches: [ resolve_unit_tests ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '**/.gitignore'
      - '**/.editorconfig'

jobs:
  test:
    name: Test on Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests with coverage
      run: npm run test:coverage
      env:
        CI: true

    # Note: The Codecov token is only required for the main repository
    # For forks, this step will be skipped due to the repository check
    - name: Upload coverage to Codecov
      if: github.event_name == 'push' && matrix.node-version == '18.x' && github.repository == 'SevWren/MuellerEuchre'
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN || '' }}
        file: ./coverage/lcov.info
        fail_ci_if_error: false

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      run: npx eslint .

    - name: Check formatting
      run: npx prettier --check .

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build --if-present
